services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
    - "3001:80"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    depends_on:
      - backend
